### PR TITLE
Add option for developers to include/exclude words from inclusivelint

### PR DESCRIPTION
**Pull request by squassina**
This PR will close issues #9 and #8

### CODE REVIEW

**Comment by Guilhermeslucas** [comment]
Lee, the other thing that would do is add the parameters to the pipeline that we are using for testing in this repo! This way anyone that wants to try our action will easily be able to do it!

**Comment by Guilhermeslucas** [comment]
Also, it should be nice to throw a error if the path to the file doesn't exist!

**Comment by squassina** [comment]
Now throwing an error if file not found:
 image

**Comment by Guilhermeslucas** [comment]
Ill close this one since we are migrating to use the typescript library

**Pull request closed without merging**
